### ISSUE TITLE
Google form link in readme

### ISSUE THREAD

**Issue by HBSaddiq** [CHATS-lab/persuasive_jailbreaker#3]
Hi there,

This work is super interesting, thanks! I would be interested in replicating some of the findings from this paper. Could you provide the google form to request access to the data used to create the persuasive paraphraser? I wasn't able to find it in the readme.

Many thanks!

**Comment by hopelin99** [comment]
Hi, 
This is Hongpeng. I appreciate your interest in our work! We have updated the [Reproducibility and Codes](https://github.com/CHATS-lab/persuasive_jailbreaker#reproducibility-and-codes) section in the README. You can now find the process for training a persuasive paraphraser and the Google Form for requesting the jailbreak result data on advbench.
